openapi: 3.0.1
info:
  title: Swagger Cliente - OpenAPI 3.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.26
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: cliente
    description: Operaciones sobre Cliente
security:
  - ApiKeyAuth: [ ]
paths:
  /api/clients:
    get:
      tags:
        - cliente
      summary: Lista los clientes.
      description: Lista los clientes.
      operationId: list
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
    post:
      tags:
        - cliente
      summary: Crea un cliente.
      description: Crea un cliente.
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDto"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
  /api/clients/stddev:
    get:
      tags:
        - cliente
      summary: Calcula la desviaci칩n est치ndar de las edades de los clientes.
      description: Calcula la desviaci칩n est치ndar de las edades de los clientes.
      operationId: standarDesviation
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: number
                format: double
  /api/clients/generation/{id}:
    get:
      tags:
        - cliente
      summary: Devuelve la generacion a la que pertence un cliente.
      description: Devuelve la generacion a la que pertence un cliente, recibe como parametro un cliente.
      operationId: generation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/clients/average:
    get:
      tags:
        - cliente
      summary: Devuelve el promedio de edades de los clientes.
      description: Devuelve el promedio de edades de los clientes.
      operationId: average
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: number
                format: double
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        details:
          type: array
          items:
            type: string
    ClientDto:
      required:
        - age
        - birthday
        - firstname
        - lastname
      type: object
      properties:
        firstname:
          minLength: 1
          type: string
        lastname:
          minLength: 1
          type: string
        age:
          type: integer
          format: int32
        birthday:
          type: string
          format: date
    Client:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        lastname:
          type: string
        age:
          type: integer
          format: int32
        birthday:
          type: string
          format: date
        flgdel:
          type: boolean
